// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Board struct {
	ID    string  `json:"_id"`
	Name  string  `json:"name"`
	Lists []*List `json:"lists"`
}

type Card struct {
	ID           string  `json:"_id"`
	Name         string  `json:"name"`
	DueDate      *string `json:"dueDate"`
	ParentListID string  `json:"parentListId"`
}

type List struct {
	ID            string  `json:"_id"`
	Name          string  `json:"name"`
	ParentBoardID string  `json:"parentBoardId"`
	Cards         []*Card `json:"cards"`
}

type NewBoard struct {
	Name string `json:"name"`
}

type NewCard struct {
	Name         string  `json:"name"`
	DueDate      *string `json:"dueDate"`
	ParentListID string  `json:"parentListId"`
}

type NewList struct {
	Name          string `json:"name"`
	ParentBoardID string `json:"parentBoardId"`
}
