// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Card struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	DueDate      *string `json:"dueDate"`
	ParentListID string  `json:"parentListId"`
}

type List struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Cards []*Card `json:"cards"`
}

type NewCard struct {
	Name         string  `json:"name"`
	DueDate      *string `json:"dueDate"`
	ParentListID string  `json:"parentListId"`
}

type NewList struct {
	Name string `json:"name"`
}
